```{r}

name <- c("joy","boyo")
name

x <- 1:20

y <- seq(1,9,by=2)

z <- c(16,"a")

met <- matrix(y,nrow=2,ncol=3)

met

```

```{r}
x <- 5:9
y <- 11:20
z <- cbind(x,y)
colnames(z) <- c("age", "height")
z

```
````{r}
X <- 1:16
Y <- 17:32
M <- rbind(X,Y)
Q <- cbind(X,Y)
rownames(M) <- c("business_index","production")
colnames(Q) <- c("business_index","production")
M
Q
M[1,15]
Q[15]
```


```{r}

m <- list(50,"b",TRUE,1+4i)
x <- list(a=1,b="c",c=3)
x$a

```

```{r}
num <-c(11,11,11,22,33,11,22,33,44)

as.factor(num)
barplot(num)
hist(num)
pie(num[3:7])
is.na(num)
sum(is.na(num))
```

```{r}
emp.data <- data.frame(emp_id= c(1:5),
                       emp_name = c("Rick","Dan","Mike","Ryan","Gary"),
                       salary = c(3000,5555,6453,4635,6446))
emp.data

```

```{r}
a <- c("b","d","f","g","e")
x <- c("a","b","c", "d", "e")
x[x >= "e"]

```

```{r}
x <- matrix(1:12,3,4)
# x[1,2]
x[1,2, drop=FALSE]
x[1,,drop=FALSE]

x[2:3,2:4]


```

```{r}
x <- matrix(1:16,4,4)
colnames(x)<- c("y1","y2","y3","y4")
rownames(x)<- c("x1","x2","x3","x4")
x
x[2,1]
x[1:3,3:4]
```